### ISSUE TITLE
jekyll build error:  no implicit conversion of Hash into String

### ISSUE THREAD

**Issue by Stargator** [jekyll/jekyll-feed#59]
After updating from github-pages 36 to 37 (and 38) and adding jekyll-feed to the config.yml's gem section:

```yaml
gems:
   - jekyll-feed
```

When running ```bundle exec jekyll build``` I get this error __jekyll 2.4.0 | Error:  no implicit conversion of Hash into String__.

After I did bundle update, I noticed the only other gems that were updated was jekyll-feed 0.3.0 (was 0.2.3).

So something changed between 0.2.3 and 0.3.0 of jekyll-feed.

Not only does it occur on my CentOS machine, but also on when CodeShip is making a build of it.

**Comment by parkr** [comment]
Can you run with `--trace`?

**Comment by Stargator** [comment]
Yes the output is as follows

```
[root@mcmahon-dev stargator.github.io-jekyll-now-copy]# bundle exec jekyll build --trace
Configuration file: /root/Desktop/SoftwareProjects/Bitbucket_Projects/jekyll-now-copy/_config.yml
            Source: content
       Destination: output
      Generating... 
/usr/local/lib/ruby/gems/2.2.0/gems/jekyll-2.4.0/lib/jekyll.rb:124:in `expand_path': no implicit conversion of Hash into String (TypeError)
        from /usr/local/lib/ruby/gems/2.2.0/gems/jekyll-2.4.0/lib/jekyll.rb:124:in `sanitized_path'
        from /usr/local/lib/ruby/gems/2.2.0/gems/jekyll-feed-0.3.0/lib/jekyll-feed.rb:94:in `feed_exists?'
        from /usr/local/lib/ruby/gems/2.2.0/gems/jekyll-feed-0.3.0/lib/jekyll-feed.rb:54:in `generate'
        from /usr/local/lib/ruby/gems/2.2.0/gems/jekyll-2.4.0/lib/jekyll/site.rb:251:in `block in generate'
        from /usr/local/lib/ruby/gems/2.2.0/gems/jekyll-2.4.0/lib/jekyll/site.rb:250:in `each'
        from /usr/local/lib/ruby/gems/2.2.0/gems/jekyll-2.4.0/lib/jekyll/site.rb:250:in `generate'
        from /usr/local/lib/ruby/gems/2.2.0/gems/jekyll-2.4.0/lib/jekyll/site.rb:45:in `process'
        from /usr/local/lib/ruby/gems/2.2.0/gems/jekyll-2.4.0/lib/jekyll/command.rb:28:in `process_site'
        from /usr/local/lib/ruby/gems/2.2.0/gems/jekyll-2.4.0/lib/jekyll/commands/build.rb:55:in `build'
        from /usr/local/lib/ruby/gems/2.2.0/gems/jekyll-2.4.0/lib/jekyll/commands/build.rb:33:in `process'
        from /usr/local/lib/ruby/gems/2.2.0/gems/jekyll-2.4.0/lib/jekyll/commands/build.rb:17:in `block (2 levels) in init_with_program'
        from /usr/local/lib/ruby/gems/2.2.0/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `call'
        from /usr/local/lib/ruby/gems/2.2.0/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `block in execute'
        from /usr/local/lib/ruby/gems/2.2.0/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `each'
        from /usr/local/lib/ruby/gems/2.2.0/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `execute'
        from /usr/local/lib/ruby/gems/2.2.0/gems/mercenary-0.3.5/lib/mercenary/program.rb:42:in `go'
        from /usr/local/lib/ruby/gems/2.2.0/gems/mercenary-0.3.5/lib/mercenary.rb:19:in `program'
        from /usr/local/lib/ruby/gems/2.2.0/gems/jekyll-2.4.0/bin/jekyll:18:in `<top (required)>'
        from /usr/local/bin/jekyll:23:in `load'
        from /usr/local/bin/jekyll:23:in `<main>'
```

**Comment by parkr** [comment]
Looks like it returned a `Hash` for `path`. What does your `feed` directive in your config look like?

**Comment by Stargator** [comment]
```yaml
feed:
  path: {{ site.feed_dir }}
```

I thought since that worked before then it wouldn't be a problem. But removing  the liquid tag with the actual value did resolve the issue.

Was that not an allowed practice before?

**Comment by parkr** [comment]
It's ok if that value is pushed through liquid, but in this case it's not. You need to set that to the feed dir path directly.
